program: cnn.py
method: bayes
metric:
  name: val_loss
  goal: minimize
parameters:
  lr: 
    min: 0.00001
    max: 0.1
  batch_size:
    values: [16, 32, 64, 128]
  epochs:
    values: [5, 10, 15, 20]
  num_conv_blocks:
    values: [2,3]
  optimizer:
    values: ["adam", "sgd"]
    